### PR TITLE
Fixed bug with argparse and made search case-insensitive

### PR DESCRIPTION
**Pull request by Crypto-Cat**
Fixed bug with argparse (fetch_term and base_dir errors when using 'list -f INT' or 'search -f INT'). Also made search case-insensitive.

### CODE REVIEW

**Comment by esp0xdeadbeef** [comment]
Fixed my problems with `wordlistctl` indeed, couldn't download the word list `usernames.tar.gz` otherwise, thanks.
image

Somehow your list contains more usernames, while the `repo.json` is exactly the same?

**Comment by Crypto-Cat** [comment]
Great 🙂 I made search+fetch case insensitive as well so that's why the extra wordlists, e.g. you searched "usernames" so "FacebookUsernames" wouldn't be detected in the original version.

**Review by ikstream — COMMENTED** [review]
code lgtm, but haven't tested yet.

Thanks so far for your contribution. I will try to test it asap.

**Comment by ikstream** [comment]
Sorry for the delay, I have been afk for quite a while. Thank you again for your contribution.

**Pull request merged**
