### PR TITLE
added support for normalp .zip files

### PR DESCRIPTION
**Pull request by Sable-20**
why.... why is this what im doing

i did this on the web im opening a pr for the requests.txt as well

### CODE REVIEW

**Comment by noraj** [comment]
> why.... why is this what im doing
> 
> i did this on the web im opening a pr for the requests.txt as well

I don't understand your comment.

**Comment by Sable-20** [comment]
> > why.... why is this what im doing
> > i did this on the web im opening a pr for the requests.txt as well
> 
> I don't understand your comment.

xD i just meant i dont know why i did this on the web

i didnt fork the repo I made the edits on the web app

**Comment by aancw** [comment]
> i did this on the web im opening a pr for the requests.txt as well

You only submit py file

**Comment by aancw** [comment]
Please don't use 2 PR, you can push commit to one PR and it's same.

https://github.com/BlackArch/wordlistctl/pull/15

**Comment by noraj** [comment]
@Sable-20 Even on the web, when editing a file for creating your 1st PR, github will automatically create your a fork. Then you can go on your fork branch (typically patch-1) and modify a second file here, so the two commit are on the same PR.

**Comment by noraj** [comment]
I made b5a24ba9e1499accc6daf3aca1f1fdf357f00769 that close #15

**Comment by sepehrdaddev** [comment]
@Sable-20, Thank you so much for this Awesome PR,
Unfortunately I can't merge it since there are no wordlists in the wordlistctl repository that is in zip format.

**Pull request closed without merging**
